
import { GoogleGenAI, Type } from "@google/genai";

const getAiClient = () => {
  // Safe access for process.env in browser environments
  const apiKey = (typeof process !== 'undefined' && process.env) 
    ? process.env.API_KEY 
    : undefined;

  if (!apiKey) {
    console.warn("API_KEY is not set in the environment.");
    return null;
  }
  return new GoogleGenAI({ apiKey });
};

export const parseOrderText = async (text: string): Promise<any> => {
  const ai = getAiClient();
  if (!ai) throw new Error("API Key missing");

  const prompt = `
    You are a smart procurement assistant. Analyze the following Chinese or English text which describes a procurement order.
    Extract the following details:
    - itemName: The name of the product (Keep it concise, translate to Chinese if mixed).
    - quantity: Number of items (number).
    - priceUSD: Price per unit in USD (number).
    - buyerAddress: The full shipping address including name and phone if available.
    - platform: The buying platform (e.g. Amazon, Taobao, 1688).
    - platformOrderId: The order ID generated by the buying platform (e.g. Amazon order number like 114-1234567-1234567), if present.
    
    If a field is missing, make a reasonable guess based on context or leave it null.
    
    Example Input: "帮我买5个iPhone 15手机壳，发到深圳市南山区科技园，李四 13800000000，单价12美金，亚马逊买，订单号是 112-3333333-4444444"
    Example Output JSON: {"itemName": "iPhone 15手机壳", "quantity": 5, "priceUSD": 12, "buyerAddress": "深圳市南山区科技园，李四 13800000000", "platform": "Amazon", "platformOrderId": "112-3333333-4444444"}
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: {
        parts: [
           { text: prompt },
           { text: `Input text to parse: "${text}"` }
        ]
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            itemName: { type: Type.STRING },
            quantity: { type: Type.NUMBER },
            priceUSD: { type: Type.NUMBER },
            buyerAddress: { type: Type.STRING },
            platform: { type: Type.STRING },
            platformOrderId: { type: Type.STRING },
          }
        }
      }
    });
    
    if (response.text) {
        return JSON.parse(response.text);
    }
    return null;
  } catch (error) {
    console.error("Gemini Parse Error:", error);
    throw error;
  }
};

export const parseOrderImage = async (base64Image: string): Promise<any> => {
    const ai = getAiClient();
    if (!ai) throw new Error("API Key missing");

    // Remove header if present (e.g., "data:image/png;base64,")
    const base64Data = base64Image.split(',')[1] || base64Image;

    const prompt = `
      Analyze this image of a product order, shopping cart, or chat log.
      Extract the order details into JSON format.
      - itemName: Product name.
      - quantity: Quantity.
      - priceUSD: Price in USD (if symbol is ¥/RMB, convert approx or keep number).
      - buyerAddress: Address if visible.
      - platform: Platform name (Amazon, eBay, etc) if recognizable.
      - platformOrderId: Order ID if visible.
    `;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash", // Flash supports vision
            contents: {
                parts: [
                    { text: prompt },
                    { 
                        inlineData: {
                            mimeType: "image/jpeg", // Assuming generic image type, API is flexible
                            data: base64Data
                        }
                    }
                ]
            },
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        itemName: { type: Type.STRING },
                        quantity: { type: Type.NUMBER },
                        priceUSD: { type: Type.NUMBER },
                        buyerAddress: { type: Type.STRING },
                        platform: { type: Type.STRING },
                        platformOrderId: { type: Type.STRING },
                    }
                }
            }
        });

        if (response.text) {
            return JSON.parse(response.text);
        }
        return null;
    } catch (error) {
        console.error("Gemini Image Parse Error:", error);
        throw error;
    }
};

export const generateStatusUpdate = async (order: any): Promise<string> => {
    const ai = getAiClient();
    if (!ai) return "Error: API Key missing";

    const prompt = `
      Create a polite notification message in Chinese to the customer about their order status.
      
      Order Details:
      Item: ${order.itemName}
      Current Status: ${order.status}
      Tracking Number: ${order.trackingNumber || 'Not available yet'}
      
      The tone should be professional and reassuring.
      Only return the message content.
    `;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt
        });
        return response.text || "Could not generate message.";
    } catch (e) {
        console.error(e);
        return "Error generating message.";
    }
}
