
import { GoogleGenAI, Type } from "@google/genai";

// Initialize the Google GenAI client following senior engineer guidelines.
// Safely handle cases where API_KEY might be undefined during initial load.
const getApiKey = () => {
    try {
        return process.env.API_KEY || '';
    } catch (e) {
        return '';
    }
};

const ai = new GoogleGenAI({ apiKey: getApiKey() });

export const parseOrderText = async (text: string): Promise<any> => {
  if (!getApiKey()) {
      console.warn("Gemini API Key is missing. Parsing will fail.");
  }

  const prompt = `
    You are a smart procurement assistant. Analyze the following Chinese or English text which describes a procurement order.
    Extract the following details:
    - itemName: The name of the product (Keep it concise, translate to Chinese if mixed).
    - quantity: Number of items (number).
    - priceUSD: Price per unit in USD (number).
    - buyerAddress: The full shipping address including name and phone if available.
    - platform: The buying platform (e.g. Amazon, Taobao, 1688).
    - platformOrderId: The order ID generated by the buying platform (e.g. Amazon order number like 114-1234567-1234567), if present.
    - clientOrderId: The client's reference number or internal order ID if mentioned (e.g. "客户单号: ABC-123").
    
    If a field is missing, make a reasonable guess based on context or leave it null.
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: {
        parts: [
           { text: prompt },
           { text: `Input text to parse: "${text}"` }
        ]
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            itemName: { type: Type.STRING },
            quantity: { type: Type.NUMBER },
            priceUSD: { type: Type.NUMBER },
            buyerAddress: { type: Type.STRING },
            platform: { type: Type.STRING },
            platformOrderId: { type: Type.STRING },
            clientOrderId: { type: Type.STRING },
          }
        }
      }
    });
    
    if (response.text) {
        return JSON.parse(response.text);
    }
    return null;
  } catch (error) {
    console.error("Gemini Parse Error:", error);
    throw error;
  }
};

export const parseOrderImage = async (base64Image: string): Promise<any> => {
    const base64Data = base64Image.split(',')[1] || base64Image;

    const prompt = `
      Analyze this image of a product order, shopping cart, or chat log.
      Extract the order details into JSON format.
      - itemName: Product name.
      - quantity: Quantity.
      - priceUSD: Price in USD.
      - buyerAddress: Address if visible.
      - platform: Platform name.
      - platformOrderId: Order ID.
      - clientOrderId: Client/Customer Order ID.
    `;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: {
                parts: [
                    { text: prompt },
                    { 
                        inlineData: {
                            mimeType: "image/jpeg",
                            data: base64Data
                        }
                    }
                ]
            },
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        itemName: { type: Type.STRING },
                        quantity: { type: Type.NUMBER },
                        priceUSD: { type: Type.NUMBER },
                        buyerAddress: { type: Type.STRING },
                        platform: { type: Type.STRING },
                        platformOrderId: { type: Type.STRING },
                        clientOrderId: { type: Type.STRING },
                    }
                }
            }
        });

        if (response.text) {
            return JSON.parse(response.text);
        }
        return null;
    } catch (error) {
        console.error("Gemini Image Parse Error:", error);
        throw error;
    }
};

export const generateStatusUpdate = async (order: any): Promise<string> => {
    const prompt = `
      Create a polite notification message in Chinese to the customer about their order status.
      Item: ${order.itemName}, Status: ${order.status}, Order Ref: ${order.clientOrderId || 'N/A'}.
      Professional tone.
    `;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: prompt
        });
        return response.text || "无法生成消息。";
    } catch (e) {
        return "消息生成错误。";
    }
};

export const parseNaturalLanguageSearch = async (query: string): Promise<any> => {
  const prompt = `
    Convert this natural language search query for orders into a JSON filter object.
    Current Date: ${new Date().toISOString().split('T')[0]}
    Query: "${query}"
  `;

  try {
     const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
         responseSchema: {
          type: Type.OBJECT,
          properties: {
            startDate: { type: Type.STRING, nullable: true },
            endDate: { type: Type.STRING, nullable: true },
            platform: { type: Type.STRING, nullable: true },
            status: { type: Type.STRING, nullable: true },
            keyword: { type: Type.STRING, nullable: true },
          }
        }
      }
    });

    if (response.text) {
        return JSON.parse(response.text);
    }
    return null;
  } catch (error) {
      return null;
  }
};
