
import { GoogleGenAI, Type } from "@google/genai";

// Fixed: Correct initialization with named parameter and direct environment variable access
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const parseOrderText = async (text: string): Promise<any> => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-pro-preview", // Complex extraction task
      contents: `Input text to parse: "${text}"`,
      config: {
        // Fixed: Moved instructions to systemInstruction for better performance
        systemInstruction: `You are a smart procurement assistant. Analyze the following Chinese or English text which describes a procurement order.
        Extract the following details into a JSON object:
        - itemName: The name of the product (Keep it concise, translate to Chinese if mixed).
        - quantity: Number of items (number).
        - priceUSD: Price per unit in USD (number).
        - buyerAddress: The full shipping address including name and phone if available.
        - platform: The buying platform (e.g. Amazon, Taobao, 1688).
        - platformOrderId: The order ID generated by the buying platform (e.g. Amazon order number like 114-1234567-1234567), if present.
        - clientOrderId: The internal procurement reference number (采购内部单号) if mentioned (e.g. "CG-2024-001" or "内部单号: XYZ").
        
        If a field is missing, make a reasonable guess based on context or leave it null.`,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            itemName: { type: Type.STRING },
            quantity: { type: Type.NUMBER },
            priceUSD: { type: Type.NUMBER },
            buyerAddress: { type: Type.STRING },
            platform: { type: Type.STRING },
            platformOrderId: { type: Type.STRING },
            clientOrderId: { type: Type.STRING },
          }
        }
      }
    });
    
    if (response.text) {
        return JSON.parse(response.text);
    }
    return null;
  } catch (error) {
    console.error("Gemini Parse Error:", error);
    throw error;
  }
};

export const parseOrderImage = async (base64Image: string): Promise<any> => {
    const base64Data = base64Image.split(',')[1] || base64Image;

    try {
        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview", // High-performance multimodal
            contents: {
                parts: [
                    { 
                        inlineData: {
                            mimeType: "image/jpeg",
                            data: base64Data
                        }
                    }
                ]
            },
            config: {
                // Fixed: Moved prompt instructions to systemInstruction
                systemInstruction: `Analyze this image of a product order, shopping cart, or chat log.
                Extract the order details into JSON format.
                - itemName: Product name.
                - quantity: Quantity.
                - priceUSD: Price in USD.
                - buyerAddress: Address if visible.
                - platform: Platform name.
                - platformOrderId: Order ID if visible.
                - clientOrderId: Internal procurement reference number (采购内部单号) if visible.`,
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        itemName: { type: Type.STRING },
                        quantity: { type: Type.NUMBER },
                        priceUSD: { type: Type.NUMBER },
                        buyerAddress: { type: Type.STRING },
                        platform: { type: Type.STRING },
                        platformOrderId: { type: Type.STRING },
                        clientOrderId: { type: Type.STRING },
                    }
                }
            }
        });

        if (response.text) {
            return JSON.parse(response.text);
        }
        return null;
    } catch (error) {
        console.error("Gemini Image Parse Error:", error);
        throw error;
    }
};

export const generateStatusUpdate = async (order: any): Promise<string> => {
    try {
        const response = await ai.models.generateContent({
            model: "gemini-3-flash-preview",
            contents: `Order Details: Item: ${order.itemName}, Status: ${order.status}, Internal Ref: ${order.clientOrderId || ''}`,
            config: {
                // Fixed: Using systemInstruction for role definition
                systemInstruction: "You are a professional customer service agent. Create a polite, reassuring notification message in Chinese to the customer about their order status. Only return the final message text."
            }
        });
        return response.text || "Could not generate message.";
    } catch (e) {
        console.error(e);
        return "Error generating message.";
    }
};

export const parseNaturalLanguageSearch = async (query: string): Promise<any> => {
  try {
     const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: `Input Query: "${query}"`,
      config: {
        // Fixed: Moved complexity into systemInstruction
        systemInstruction: `You are a data query parser. Convert this natural language search query for a procurement order system into a JSON filter object.
        Current Date: ${new Date().toISOString().split('T')[0]}`,
        responseMimeType: "application/json",
         responseSchema: {
          type: Type.OBJECT,
          properties: {
            startDate: { type: Type.STRING, nullable: true },
            endDate: { type: Type.STRING, nullable: true },
            platform: { type: Type.STRING, nullable: true },
            status: { type: Type.STRING, nullable: true },
            keyword: { type: Type.STRING, nullable: true },
          }
        }
      }
    });

    if (response.text) {
        return JSON.parse(response.text);
    }
    return null;
  } catch (error) {
      console.error("Gemini Search Parse Error", error);
      return null;
  }
};
